services:
  gluetun:
    image: qmcgaw/gluetun:v3.39.1
    # container_name: gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=United States
      - TZ=America/New_York
      - UPDATER_PERIOD=24h
      - DOT_PROVIDERS=quad9
      - FIREWALL_OUTBOUND_SUBNETS=172.21.0.0/16
    env_file:
      - ../../secrets/gluetun.env
    restart: unless-stopped
    labels:
      caddy_0: torrent.home.mliebman.com
      caddy_0.reverse_proxy: "{{upstreams 8080}}"
      caddy_0.tls: internal
      caddy_1: bookbounty.home.mliebman.com
      caddy_1.reverse_proxy: "{{upstreams 5000}}"
      caddy_1.tls: internal
    networks:
      - caddy
      - internal
  readarr:
    image: lscr.io/linuxserver/readarr:nightly-version-0.4.1.2648
    container_name: readarr
    volumes:
      - ./data/readarr:/config
      - ./data:/data
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=101
    env_file:
      - ../../secrets/readarr.env
    restart: unless-stopped
    networks:
      - caddy
      - internal
    labels:
      caddy: readarr.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 8787}}"
      caddy.tls: internal
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:version-5.0.0-r2
    container_name: qbittorrent
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=101
    volumes:
      - ./data/qbittorrent:/config
      - ./data/torrents:/data/torrents
    restart: unless-stopped
    network_mode: service:gluetun
  bookbounty:
    image: thewicklowwolf/bookbounty:0.1.7
    container_name: bookbounty
    volumes:
      - ./data/bookbounty:/bookbounty/config
      - ./data/media/books/_unprocessed:/bookbounty/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: service:gluetun
    env_file:
      - path: ../../secrets/bookbounty.env
        required: false
    environment:
      - selected_path_type=file
      - library_scan_on_completion=True
      - readarr_address=http://172.21.0.2:8787
      - PUID=1000
      - PGID=101
networks:
  internal:
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
  caddy:
    external: true
