services:
  gluetun:
    image: qmcgaw/gluetun:v3.39.1
    # container_name: gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=United States
      - TZ=America/New_York
      - UPDATER_PERIOD=24h
      - DOT_PROVIDERS=quad9
    env_file:
      - ../../secrets/gluetun.env
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:nightly-version-0.4.1.2648
    container_name: readarr
    volumes:
      - ./data/readarr:/config
      - ./data/books:/books
      - ./data/downloads:/downloads
    env_file:
      - ../../secrets/readarr.env
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: readarr.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 8787}}"
      caddy.tls: internal
networks:
  caddy:
    external: true
