services:
  gluetun:
    image: qmcgaw/gluetun:v3.39.1
    # container_name: gluetun
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./data/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=United States
      - TZ=America/New_York
      - UPDATER_PERIOD=24h
      - DOT_PROVIDERS=quad9
    env_file:
      - ../../secrets/gluetun.env
    restart: unless-stopped
    labels:
      caddy_0: torrent.home.mliebman.com
      caddy_0.reverse_proxy: "{{upstreams 8080}}"
      caddy_0.tls: internal
    networks:
      - caddy
  readarr:
    image: lscr.io/linuxserver/readarr:nightly-version-0.4.1.2648
    container_name: readarr
    volumes:
      - ./data/readarr:/config
      - ./data:/data
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=101
    env_file:
      - ../../secrets/readarr.env
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: readarr.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 8787}}"
      caddy.tls: internal
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:version-5.0.0-r2
    container_name: qbittorrent
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=101
    volumes:
      - ./data/qbittorrent:/config
      - ./data/torrents:/data/torrents
    restart: unless-stopped
    network_mode: service:gluetun
networks:
  caddy:
    external: true
