services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: it-tools.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal
  stirling-pdf:
    image: stirlingtools/stirling-pdf:0.45.0
    container_name: pdf-tools
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: pdf-tools.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: internal
    volumes:
      - ./stirling-pdf/trainingData:/usr/share/tessdata
      - ./stirling-pdf/extraConfig:/configs
    environment:
      - LANGS=en_US
      - DOCKER_ENABLE_SECURITY=false
      - LEGAL_TERMSANDCONDITIONS=
      - LEGAL_PRIVACYPOLICY=
      - UI_APPNAME=PDF Tools
networks:
  caddy:
    external: true
