services:
  it-tools:
    image: corentinth/it-tools:2024.10.22-7ca5933
    container_name: it-tools
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: it-tools.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal
networks:
  caddy:
    external: true
