services:
  backrest:
    image: garethgeorge/backrest:v1.7.2
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/New_York # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: backup.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 9898}}"
      caddy.tls: internal
  syncthing:
    image: syncthing/syncthing:1.29.2
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=101
    volumes:
      - ./syncthing:/var/syncthing
      - ../wallos/db:/var/syncthing-storage/wallos
      - /etc/docker-secrets/:/var/syncthing-storage/secrets
      - /var/backup:/var/syncthing-storage/backup
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - caddy
    labels:
      caddy: syncthing.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 8384}}"
      caddy.tls: internal
networks:
  caddy:
    external: true
