services:
  backrest:
    image: garethgeorge/backrest:v1.6.1
    container_name: backrest
    hostname: backrest
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
    environment:
      - BACKREST_DATA=/data # path for backrest data. restic binary and the database are placed here.
      - BACKREST_CONFIG=/config/config.json # path for the backrest config file.
      - XDG_CACHE_HOME=/cache # path for the restic cache which greatly improves performance.
      - TZ=America/New_York # set the timezone for the container, used as the timezone for cron jobs.
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: backup.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 9898}}"
      caddy.tls: internal
networks:
  caddy:
    external: true
