services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.83.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      caddy: n8n.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 5678}}"
      caddy.tls: internal
    networks:
      - caddy
volumes:
  n8n_data:
    external: true
networks:
  caddy:
    external: true
