services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.4
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/michael/docker/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    env_file:
      - /etc/docker-secrets/homepage.env
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: dashboard.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls: internal
networks:
  caddy:
    external: true
