services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.12
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "export HOMEPAGE_VAR_VM0_TOKEN_ID=$$(cat /run/secrets/HOMEPAGE_VAR_VM0_TOKEN_ID) ;
         export HOMEPAGE_VAR_VM0_SECRET=$$(cat /run/secrets/HOMEPAGE_VAR_VM0_SECRET) ;
         export HOMEPAGE_VAR_UPTIME_ROBOT_RO_KEY=$$(cat /run/secrets/HOMEPAGE_VAR_UPTIME_ROBOT_RO_KEY) ;
         export HOMEPAGE_GHOST_FOLIO_KEY=$$(cat /run/secrets/HOMEPAGE_GHOST_FOLIO_KEY) ;
         export HOMEPAGE_QBITTORRENT_USERNAME=$$(cat /run/secrets/HOMEPAGE_QBITTORRENT_USERNAME) ;
         export HOMEPAGE_QBITTORRENT_PASSWORD=$$(cat /run/secrets/HOMEPAGE_QBITTORRENT_PASSWORD) ;
         export HOMEPAGE_READARR_KEY=$$(cat /run/secrets/HOMEPAGE_READARR_KEY) ;
         export HOMEPAGE_VAR_PORTAINER_USERNAME=$$(cat /run/secrets/HOMEPAGE_VAR_PORTAINER_USERNAME) ;
         export HOMEPAGE_VAR_PORTAINER_PASSWORD=$$(cat /run/secrets/HOMEPAGE_VAR_PORTAINER_PASSWORD) ;
         source /docker-entrypoint.sh",
      ]
    restart: unless-stopped
    networks:
      - caddy
    labels:
      caddy: dashboard.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls: internal
    secrets:
      - HOMEPAGE_VAR_VM0_TOKEN_ID
      - HOMEPAGE_VAR_VM0_SECRET
      - HOMEPAGE_VAR_UPTIME_ROBOT_RO_KEY
      - HOMEPAGE_GHOST_FOLIO_KEY
      - HOMEPAGE_QBITTORRENT_USERNAME
      - HOMEPAGE_QBITTORRENT_PASSWORD
      - HOMEPAGE_READARR_KEY
      - HOMEPAGE_VAR_PORTAINER_USERNAME
      - HOMEPAGE_VAR_PORTAINER_PASSWORD
networks:
  caddy:
    external: true
secrets:
  HOMEPAGE_VAR_VM0_TOKEN_ID:
    external: true
  HOMEPAGE_VAR_VM0_SECRET:
    external: true
  HOMEPAGE_VAR_UPTIME_ROBOT_RO_KEY:
    external: true
  HOMEPAGE_GHOST_FOLIO_KEY:
    external: true
  HOMEPAGE_QBITTORRENT_USERNAME:
    external: true
  HOMEPAGE_QBITTORRENT_PASSWORD:
    external: true
  HOMEPAGE_READARR_KEY:
    external: true
  HOMEPAGE_VAR_PORTAINER_USERNAME:
    external: true
  HOMEPAGE_VAR_PORTAINER_PASSWORD:
    external: true
