services:
  portainer:
    image: portainer/portainer-ee:2.24.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - caddy
    labels:
      caddy: portainer.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.tls: internal    
networks:
  caddy:
    external: true
volumes:
  portainer_data:
