services:
  dockge:
    image: louislam/dockge:1.4.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /home/michael/docker:/home/michael/docker
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/home/michael/docker
    labels:
      caddy: gitops.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 5001}}"
      caddy.tls: internal
    networks:
      - caddy
  dockge-gitops:
    image: ghcr.io/ebaldebo/dockge-gitops:v0.2.1
    container_name: dockge-gitops
    restart: unless-stopped
    environment:
      - REPO_URL=https://github.com/michael-liebman/homelab.git # required
      - POLLING_RATE=10m # optional
      # Needs to be the same as the stacks directory in the dockge container
      - DOCKGE_STACKS_DIR=/home/michael/docker
    volumes:
      # Needs to be the same as the stacks directory in the dockge container
      - /home/michael/docker:/home/michael/docker
      - /home/michael/secrets:/env # optional path to .env file
networks:
  caddy:
    external: true
