services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.12.4
    restart: unless-stopped
    group_add:
      - 101
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ../../secrets/doco-cd.env
    networks:
      - caddy
    labels:
      caddy: gitops.home.mliebman.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/v1/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  caddy:
    external: true
