---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github (U):
        - abbr: GH
          icon: si-github
          href: https://github.com/michaelliebman
    - Github (O):
        - abbr: GH
          icon: si-github
          href: https://github.com/michael-liebman
    - Jira:
        - abbr: JI
          icon: si-jira
          href: https://liebman.atlassian.net/jira/

- Social:
    - Reddit:
        - abbr: RE
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
