---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network & Infrastructure:
    - flyer-ds:
        href: https://flyer-ds.home.mliebman.com/
        description: Router & basement WiFi access point
        icon: openwrt
        ping: flyer-ds.home.mliebman.com
        siteMonitor: https://flyer-ds.home.mliebman.com/
    - flyer-us:
        href: https://flyer-us.home.mliebman.com/
        description: First floor WiFi access point
        icon: openwrt
        ping: flyer-us.home.mliebman.com
        siteMonitor: https://flyer-us.home.mliebman.com/
    - Print/Scan:
        href: https://print-scan.home.mliebman.com/
        icon: printer
        ping: print-scan.home.mliebman.com
    - Proxmox:
        href: https://vm0.home.mliebman.com:8006/
        description: Virtual Machine Hypervisor
        icon: proxmox
        ping: vm0.home.mliebman.com
        siteMonitor: https://vm0.home.mliebman.com:8006/
        widget:
            type: proxmox
            url: https://vm0.home.mliebman.com:8006
            username: {{HOMEPAGE_VAR_VM0_TOKEN_ID}}
            password: {{HOMEPAGE_VAR_VM0_SECRET}}
            node: vm0
    - Pi-hole:
        href: http://192.168.2.5/admin/
        description: DNS and ad blocking
        icon: pi-hole
        ping: 192.168.2.5
- RVC:
    - Home Assistant RVC:
        href: https://mlr03du7c9e421riwplae2qfz3refigs.ui.nabu.casa/
        icon: si-homeassistant
    - Go2RTC RVC:
        href: http://localhost:11984/
        description: Camera interface (requires tunnel)
        icon: mdi-cctv
    - Portainer RVC:
        href: https://localhost:9001/
        description: Server management (requires tunnel)
        icon: portainer
    - RVC HA Tunnel:
        href: http://localhost:18123/
        description: RVC Home Assistant via tunnel
        icon: si-homeassistant
- Observability:
    - Healthchecks:
        href: https://healthchecks.io/
        description: Scheduled job monitoring
        icon: healthchecks
    - UptimeRobot:
        href: https://uptimerobot.com/dashboard#mainDashboard
        description: Service monitoring
        icon: uptime-kuma
