---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network:
    - flyer-ds:
        href: https://flyer-ds.home.mliebman.com/
        description: Router & basement WiFi access point
        icon: openwrt
        ping: flyer-ds.home.mliebman.com
    - flyer-us:
        href: https://flyer-us.home.mliebman.com/
        description: First floor WiFi access point
        icon: openwrt
        ping: flyer-us.home.mliebman.com

