---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Applications:
    - Home Assistant:
        href: http://homeassistant.home.mliebman.com:8123/
        description: Automation
        icon: sh-home-assistant
        ping: homeassistant.home.mliebman.com
        siteMonitor: http://homeassistant.home.mliebman.com:8123/
    - Ghostfolio:
        href: https://investing.home.mliebman.com/
        description: Investment Porfolio Management
        icon: sh-ghostfolio
        siteMonitor: https://investing.home.mliebman.com/
        widget:
            type: ghostfolio
            url: https://investing.home.mliebman.com/
            key: "{{HOMEPAGE_GHOST_FOLIO_KEY}}"
    - Wallos:
        href: https://subscription.home.mliebman.com/
        description: Subscription Tracker
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/wallos.png
        siteMonitor: https://subscription.home.mliebman.com/
- Miscellaneous:
    - IT-Tools:
        href: https://it-tools.home.mliebman.com/
        description: A collection of tech tools
        icon: sh:it-tools
        siteMonitor: https://it-tools.home.mliebman.com/
    - PDF Tools:
        href: https://pdf-tools.home.mliebman.com/
        description: A collection of PDF tools
        icon: sh:stirling-pdf
        siteMonitor: https://pdf-tools.home.mliebman.com/
- Network & Infrastructure:
    - flyer-ds:
        href: https://flyer-ds.home.mliebman.com/
        description: Router & basement WiFi access point
        icon: openwrt
        ping: flyer-ds.home.mliebman.com
        siteMonitor: https://flyer-ds.home.mliebman.com/
    - flyer-us:
        href: https://flyer-us.home.mliebman.com/
        description: First floor WiFi access point
        icon: openwrt
        ping: flyer-us.home.mliebman.com
        siteMonitor: https://flyer-us.home.mliebman.com/
    - Netbox:
        href: https://netbox.home.mliebman.com/
        description: IP Address Management & other network info
        icon: netbox
        siteMonitor: https://netbox.home.mliebman.com/
    - Print/Scan:
        href: https://print-scan.home.mliebman.com/
        icon: printer
        ping: print-scan.home.mliebman.com
    - Proxmox:
        href: https://vm0.home.mliebman.com:8006/
        description: Virtual Machine Hypervisor
        icon: proxmox
        ping: vm0.home.mliebman.com
        siteMonitor: https://vm0.home.mliebman.com:8006/
        widget:
            type: proxmox
            url: https://vm0.home.mliebman.com:8006
            username: "{{HOMEPAGE_VAR_VM0_TOKEN_ID}}"
            password: "{{HOMEPAGE_VAR_VM0_SECRET}}"
            node: vm0
    - Technitium:
        href: http://192.168.2.5:5380/
        description: DNS and ad blocking
        icon: technitium
        ping: 192.168.2.5
        siteMonitor: http://192.168.2.5:5380/
    - Matomo:
        href: https://stats.mliebman.com/
        description: Website statistics
        icon: matomo
        ping: stats.mliebman.com
        siteMonitor: https://stats.mliebman.com/
    - N8N:
        href: https://n8n.home.mliebman.com/
        description: API automation
        icon: sh-n8n
        siteMonitor: https://n8n.home.mliebman.com
    - Backup:
        href: https://backup.home.mliebman.com/
        description: Backups
        icon: sh-restic
        siteMonitor: https://backup.home.mliebman.com
    - Syncthing:
        href: https://syncthing.home.mliebman.com/
        description: File sharing
        icon: sh-syncthing
        siteMonitor: https://syncthing.home.mliebman.com
    - Portainer:
        href: https://portainer.home.mliebman.com/
        description: Server management
        icon: portainer
        siteMonitor: https://portainer.home.mliebman.com
        widget:
            type: portainer
            url: https://portainer.home.mliebman.com
            username: "{{HOMEPAGE_VAR_PORTAINER_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PORTAINER_PASSWORD}}"
- RVC:
    - Home Assistant RVC:
        href: https://mlr03du7c9e421riwplae2qfz3refigs.ui.nabu.casa/
        icon: si-homeassistant
    - Go2RTC RVC:
        href: http://localhost:11984/
        description: Camera interface (requires tunnel)
        icon: mdi-cctv
    - Portainer RVC:
        href: https://localhost:9001/
        description: Server management (requires tunnel)
        icon: portainer
    - RVC HA Tunnel:
        href: http://localhost:18123/
        description: RVC Home Assistant via tunnel
        icon: si-homeassistant
- Observability:
    - Healthchecks:
        href: https://healthchecks.io/
        description: Scheduled job monitoring
        icon: healthchecks
    - UptimeRobot:
        href: https://uptimerobot.com/dashboard#mainDashboard
        description: Service monitoring
        icon: uptime-kuma
        widget:
            type: uptimerobot
            url: https://api.uptimerobot.com
            key: "{{HOMEPAGE_VAR_UPTIME_ROBOT_RO_KEY}}"
    - DMARC Report:
        href: https://dmarc-report.home.mliebman.com/
        description: Email delivery reports
        icon: mdi-package-check
        siteMonitor: https://dmarc-report.home.mliebman.com
